"""add firmware table

Revision ID: 028b7fd3fdd0
Revises: fcedabe5aa6b
Create Date: 2026-08-19 16:38:30.593250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028b7fd3fdd0'
down_revision: Union[str, Sequence[str], None] = 'fcedabe5aa6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ota_target_version', sa.String(length=50), nullable=True))
    op.add_column(
        'devices',
        sa.Column(
            'ota_status',
            sa.String(length=30),
            nullable=False,
            server_default='idle',
        ),
    )
    op.add_column('devices', sa.Column('ota_firmware_url', sa.String(length=500), nullable=True))
    op.add_column('devices', sa.Column('ota_checksum', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('ota_requested_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('ota_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'ota_completed_at')
    op.drop_column('devices', 'ota_requested_at')
    op.drop_column('devices', 'ota_checksum')
    op.drop_column('devices', 'ota_firmware_url')
    op.drop_column('devices', 'ota_status')
    op.drop_column('devices', 'ota_target_version')
    # ### end Alembic commands ###