"""add homes and link devices to homes

Revision ID: 2d15bee58987
Revises: 720fc330a27c
Create Date: 2026-08-14 16:14:05.454824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d15bee58987'
down_revision: Union[str, Sequence[str], None] = '720fc330a27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homes_owner_id'), 'homes', ['owner_id'], unique=False)
    op.add_column('devices', sa.Column('home_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_devices_home_id'), 'devices', ['home_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'homes', ['home_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_home_id'), table_name='devices')
    op.drop_column('devices', 'home_id')
    op.drop_index(op.f('ix_homes_owner_id'), table_name='homes')
    op.drop_table('homes')
    # ### end Alembic commands ###
