"""add device type

Revision ID: 450ea518bb39
Revises: 2d15bee58987
Create Date: 2026-08-15 06:52:20.828249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450ea518bb39'
down_revision: Union[str, Sequence[str], None] = '2d15bee58987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'devices',
        sa.Column(
            'device_type',
            sa.String(length=50),
            nullable=False,
            server_default='SMART_DEVICE',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###
