"""add sent at to device commands

Revision ID: 720fc330a27c
Revises: 93359f24c691
Create Date: 2026-08-07 17:33:46.984872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '720fc330a27c'
down_revision: Union[str, Sequence[str], None] = '93359f24c691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_commands', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.alter_column('devices', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'firmware_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.drop_constraint(op.f('devices_device_id_key'), 'devices', type_='unique')
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_secret_key'), 'devices', ['secret_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_secret_key'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.create_unique_constraint(op.f('devices_device_id_key'), 'devices', ['device_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('devices', 'firmware_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.alter_column('devices', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('device_commands', 'sent_at')
    # ### end Alembic commands ###
