"""add image_path and created_at

Revision ID: 8fc146cd926a
Revises: f2670941ea42
Create Date: 2026-07-21 13:56:48.004031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc146cd926a'
down_revision: Union[str, Sequence[str], None] = 'f2670941ea42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('detections', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'created_at')
    op.drop_column('detections', 'image_path')
    # ### end Alembic commands ###
