"""add command last attempt time

Revision ID: 947960443915
Revises: ec72fd37829f
Create Date: 2026-08-17 09:40:06.018318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947960443915'
down_revision: Union[str, Sequence[str], None] = 'ec72fd37829f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_commands', sa.Column('last_attempt_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_commands', 'last_attempt_at')
    # ### end Alembic commands ###
