"""add command attempt count

Revision ID: ec72fd37829f
Revises: 5b15d2c1c2e2
Create Date: 2026-08-17 09:34:35.267238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec72fd37829f'
down_revision: Union[str, Sequence[str], None] = '5b15d2c1c2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'device_commands',
    sa.Column(
        'attempt_count',
        sa.Integer(),
        nullable=False,
        server_default='0',
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_commands', 'attempt_count')
    # ### end Alembic commands ###
