"""add_fcm_token_to_users

Revision ID: fcedabe5aa6b
Revises: 947960443915
Create Date: 2026-08-18 17:16:40.837632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcedabe5aa6b'
down_revision: Union[str, Sequence[str], None] = '947960443915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'firmware_version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('devices', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('devices', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'OFF'::character varying"))
    op.drop_index(op.f('ix_devices_secret_key'), table_name='devices')
    op.drop_constraint(op.f('devices_home_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'homes', ['home_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_home_id_fkey'), 'devices', 'homes', ['home_id'], ['id'])
    op.create_index(op.f('ix_devices_secret_key'), 'devices', ['secret_key'], unique=False)
    op.alter_column('devices', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'OFF'::character varying"))
    op.alter_column('devices', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('devices', 'firmware_version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
